version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: wallet-db
    restart: always
    environment:
      POSTGRES_DB: WalletDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: